export const YELLOW_COLOR = "#ffc107";
// export const ORANGE_COLOR = "#fd7e14"; backup primary color
export const ORANGE_COLOR = "#1677ff";
export const ORANGE_COLOR2 = "#fd7e14"
export const BORDER_COLOR = "#a1a7af";
export const LIGHT_GRAY = "#f2f6fb";
export const TEXT_COLOR = "#303a48";
export const LINK_COLOR = "#64b8fd";
export const DARK_COLOR = "#131313";
export const SECONDARY_COLOR = "#ff7200";
export const BACKGROUND_GRAY = "#f6f6f6";
export const BODY_COLOR = "#fcfcfc";
export const RED_COLOR = "#d93843";
